version: '3'

services:
  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./web/:/usr/src/app
    env_file: .env
    environment:
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: