version: '3'

services:
  web:
    restart: always
    build: ./web
    tty: true
    expose:
      - "8000"
    volumes:
      - ./web/:/usr/src/app
      - ./web/static:/www/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/static:/www/static
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=Mexico/General

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
  static_web:
